<?php
/**
 * Mumzworld.com
 * @category    Mumzworld
 * @package     Mumzworld_PromoCampaign
 * @author      A. Dilhan Maduranga <dilhan.maduranga@mumzworld.com>
 */

class Mumzworld_PromoCampaign_Model_Coupon extends Mage_Core_Model_Abstract
{
    /**
     * @var Mumzworld_PromoCampaign_Model_Promotion $_promotion
     */
    protected $_promotion;

    /**
     * @var Mage_Sales_Model_Order $_order;
     */
    protected $_order;

    /**
     * @var Mage_SalesRule_Model_Coupon $_salesruleCoupon
     */
    protected $_salesruleCoupon;

    /**
     * Initialize resource model
     *
     */
    protected function _construct()
    {
        $this->_init('promocampaign/coupon');
    }

    /**
     * @param $promotion
     */
    public function setPromotion($promotion)
    {
        $this->_promotion = $promotion;
    }

    /**
     * @return Mumzworld_PromoCampaign_Model_Promotion
     */
    public function getPromotion()
    {
        return $this->_promotion;
    }

    /**
     * @param $order
     */
    public function setOrder($order)
    {
        $this->_order = $order;
    }

    /**
     * @return Mage_Sales_Model_Order
     */
    public function getOrder()
    {
        return $this->_order;
    }

    /**
     * @return Mage_SalesRule_Model_Coupon
     */
    public function getSalesruleCoupon()
    {
        return $this->_salesruleCoupon;
    }

    /**
     * @param $promotion
     * @param $order
     * @return $this
     */
    public function generate($promotion, $order)
    {
        $this->setOrder($order);
        $this->setPromotion($promotion);

        $this->setCampaignId($promotion->getId())
            ->setOrderId($order->getId())
            ->setCustomerId($order->getCustomerId())
            ->setCouponId($this->getPromoCouponId())
            ->save();
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPromoCouponId()
    {
        return $this->getPromoCode()->getId();
    }

    /**
     * @return false|Mage_Core_Model_Abstract
     * @throws Mage_Core_Exception
     */
    public function getPromoCode()
    {
        $salesruleId = $this->getPromotion()->getSalesruleId();

        $generator = Mage::getModel('salesrule/coupon_massgenerator');
        $generator->setPrefix('MWA-')
            ->setLength(10)
            ->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC);

        $coupon = Mage::getModel('salesrule/coupon');
        $attempt = 0;
        do {
            if ($attempt >= 10) {
                Mage::throwException(Mage::helper('promocampaign')->__('Unable to create requested Coupon.'));
            }
            $code = $generator->generateCode();
            $attempt++;
        } while ($coupon->getResource()->exists($code));

        $coupon->setRuleId($salesruleId)
            ->setUsagePerCustomer(1)
            ->setExpirationDate($this->getPromotion()->getEndDate())
            ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
            ->setCode($code)
            ->save();

        return $this->_salesruleCoupon = $coupon;
    }
}
