<?php
/**
 */
class Mumzworld_PromoCampaign_Model_Coupon extends Mage_Core_Model_Abstract
{

    protected $_promotion;

    protected $_order;

    protected $_salesruleCoupon;

    /**
     * Initialize resource model
     *
     */
    protected function _construct()
    {
        $this->_init('promocampaign/coupon');
    }

    public function setPromotion($promotion)
    {
        $this->_promotion = $promotion;
    }

    public function getPromotion()
    {
        return $this->_promotion;
    }

    public function setOrder($order)
    {
        $this->_order = $order;
    }
    public function getOrder()
    {
        return $this->_order;
    }

    public function getSalesruleCoupon()
    {
        return $this->_salesruleCoupon;
    }


    public function generate($promotion, $order)
    {
        $this->setOrder($order);
        $this->setPromotion($promotion);

        if (!$this->getId()) {
            $this->setCampaignId($promotion->getId())
                ->setOrderId($order->getId())
                ->setCustomerId($order->getCustomerId())
                ->setCouponId($this->getPromoCouponId())
                ->save();
            return $this;
        }
    }


    public function getPromoCouponId()
    {
        return $this->getPromoCode()->getId();
    }

    public function getPromoCode()
    {
        $salesruleId = $this->getPromotion()->getSalesruleId();

        $generator = Mage::getModel('salesrule/coupon_massgenerator');
        $generator->setPrefix('MWA-')
            ->setLength(10)
            ->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC);

        $coupon = Mage::getModel('salesrule/coupon');
        $attempt = 0;
        do {
            if ($attempt >= 10) {
                Mage::throwException(Mage::helper('promocampaign')->__('Unable to create requested Coupon.'));
            }
            $code = $generator->generateCode();
            $attempt++;
        } while ($coupon->getResource()->exists($code));

        $coupon->setRuleId($salesruleId)
            ->setUsagePerCustomer(1)
            ->setExpirationDate($this->getPromotion()->getEndDate())
            ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
            ->setCode($code)
            ->save();

        return $this->_salesruleCoupon = $coupon;
    }
}
